version: 2
updates:

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Zurich"
    target-branch: "main"
    labels:
      - "github-actions"
      - "dependencies"
